"""
Google Colab 노트북 생성 스크립트
"""

import json

notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {
            "provenance": [],
            "gpuType": "A100"
        },
        "kernelspec": {
            "name": "python3",
            "display_name": "Python 3"
        },
        "accelerator": "GPU"
    },
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🎯 Empathy Alignment: Baseline Model Evaluation\n",
                "\n",
                "이 노트북에서는 **Llama-3.1-8B**와 **DeepSeek-7B** 모델을 4가지 공감 메트릭으로 평가합니다.\n",
                "\n",
                "## 4가지 평가 차원\n",
                "1. **Specificity (구체성)**: Brysbaert et al. (2014)\n",
                "2. **Reflection Level (반영 수준)**: PAIR Model (Min et al., 2022)\n",
                "3. **Word Choice (단어 선택)**: NRC VAD Lexicon (Mohammad, 2018)\n",
                "4. **Diversity (다양성)**: Distinct-n (Li et al., 2016)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["---\n## 1. 환경 설정"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": ["# GPU 확인\n!nvidia-smi"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 필요한 패키지 설치\n",
                "!pip install -q transformers accelerate bitsandbytes\n",
                "!pip install -q torch\n",
                "!pip install -q huggingface_hub\n",
                "!pip install -q tqdm pandas matplotlib"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Google Drive 마운트\n",
                "from google.colab import drive\n",
                "drive.mount('/content/drive')\n",
                "\n",
                "# 프로젝트 경로 설정\n",
                "PROJECT_PATH = '/content/drive/MyDrive/empathy_alignment'\n",
                "\n",
                "# 필요한 폴더 생성\n",
                "import os\n",
                "os.makedirs(f'{PROJECT_PATH}/data', exist_ok=True)\n",
                "os.makedirs(f'{PROJECT_PATH}/models', exist_ok=True)\n",
                "os.makedirs(f'{PROJECT_PATH}/results', exist_ok=True)\n",
                "os.makedirs(f'{PROJECT_PATH}/src/metrics', exist_ok=True)\n",
                "\n",
                "print(f'Project path: {PROJECT_PATH}')\n",
                "print('Folders created!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# HuggingFace 로그인 (Llama 모델 접근을 위해 필요)\n",
                "# https://huggingface.co/settings/tokens 에서 토큰 발급\n",
                "# https://huggingface.co/meta-llama 에서 Llama 라이센스 동의 필요\n",
                "from huggingface_hub import login\n",
                "login()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["---\n## 2. 메트릭 코드 정의"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import re\n",
                "import numpy as np\n",
                "from typing import List, Dict, Optional, Union, Tuple\n",
                "from collections import Counter\n",
                "from dataclasses import dataclass, asdict\n",
                "from datetime import datetime\n",
                "import json\n",
                "\n",
                "# ========== Specificity Metric ==========\n",
                "class SpecificityMetric:\n",
                "    def __init__(self):\n",
                "        self.lexicon = {\n",
                "            'apple': 5.0, 'dog': 4.98, 'cat': 4.97, 'car': 4.95, 'house': 4.93,\n",
                "            'tree': 4.92, 'book': 4.89, 'table': 4.88, 'phone': 4.85, 'computer': 4.82,\n",
                "            'water': 4.80, 'food': 4.75, 'hand': 4.90, 'face': 4.85, 'eye': 4.88,\n",
                "            'money': 4.45, 'music': 4.20, 'weather': 4.15, 'friend': 4.10, 'family': 4.05,\n",
                "            'work': 3.95, 'home': 4.30, 'school': 4.25, 'problem': 3.50, 'situation': 3.20,\n",
                "            'experience': 3.15, 'feeling': 3.10, 'moment': 3.05, 'reason': 2.95, 'way': 2.85,\n",
                "            'time': 3.30, 'life': 3.25, 'day': 3.80, 'place': 3.75, 'idea': 2.50,\n",
                "            'hope': 2.30, 'love': 2.45, 'fear': 2.40, 'joy': 2.35, 'sadness': 2.25,\n",
                "            'anger': 2.55, 'happiness': 2.20, 'peace': 2.15, 'freedom': 2.10, 'truth': 2.05,\n",
                "            'thing': 1.95, 'something': 1.85, 'anything': 1.80, 'nothing': 1.75,\n",
                "            'understand': 2.60, 'sorry': 2.70, 'glad': 2.65, 'proud': 2.55, 'worried': 2.75,\n",
                "            'excited': 2.80, 'disappointed': 2.45, 'frustrated': 2.50, 'grateful': 2.40,\n",
                "            'anxious': 2.35, 'overwhelmed': 2.30, 'stressed': 2.85, 'relieved': 2.90,\n",
                "        }\n",
                "    \n",
                "    def compute(self, text: str) -> Dict:\n",
                "        words = re.findall(r'\\b[a-z]+\\b', text.lower())\n",
                "        if not words: return {'score': 0.0, 'coverage': 0.0}\n",
                "        scores = [self.lexicon[w] for w in words if w in self.lexicon]\n",
                "        if not scores: return {'score': 0.0, 'coverage': 0.0}\n",
                "        return {'score': float(np.mean(scores)), 'coverage': len(scores)/len(words)}\n",
                "\n",
                "print('✅ SpecificityMetric defined')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ========== Reflection Level Metric ==========\n",
                "class ReflectionLevelMetric:\n",
                "    def __init__(self):\n",
                "        self.complex_patterns = [\n",
                "            r'it seems like .+ means .+ to you', r'beneath .+ there seems to be',\n",
                "            r'on a deeper level', r'what that .+ represents',\n",
                "        ]\n",
                "        self.feeling_patterns = [\n",
                "            r\"you('re| are) feeling\", r'you feel', r'you seem',\n",
                "            r\"sounds like you('re| are)\", r'it sounds like',\n",
                "            r'that must (be|feel|have been)',\n",
                "            r\"i can (see|hear|sense|imagine) (that |how )?you\",\n",
                "        ]\n",
                "        self.simple_patterns = [\n",
                "            r'so you', r\"you('re| are) saying\", r'you mentioned',\n",
                "            r'i hear you', r'i understand', r'i see',\n",
                "            r\"that('s| is) (hard|difficult|tough|challenging)\",\n",
                "        ]\n",
                "        self.empathy_boosters = [\n",
                "            r\"i('m| am) sorry (to hear|that)\",\n",
                "            r'that must (be|have been) (really |very )?(hard|difficult|painful)',\n",
                "            r'i can only imagine', r'thank you for (sharing|telling)',\n",
                "        ]\n",
                "    \n",
                "    def compute(self, response: str, context: Optional[str] = None) -> Dict:\n",
                "        text = response.lower().strip()\n",
                "        counts = {'complex': 0, 'feeling': 0, 'simple': 0, 'booster': 0}\n",
                "        \n",
                "        for p in self.complex_patterns:\n",
                "            if re.search(p, text): counts['complex'] += 1\n",
                "        for p in self.feeling_patterns:\n",
                "            if re.search(p, text): counts['feeling'] += 1\n",
                "        for p in self.simple_patterns:\n",
                "            if re.search(p, text): counts['simple'] += 1\n",
                "        for p in self.empathy_boosters:\n",
                "            if re.search(p, text): counts['booster'] += 1\n",
                "        \n",
                "        if counts['complex'] > 0: level = 5 + min(counts['complex'], 1)\n",
                "        elif counts['feeling'] > 0: level = 3 + min(counts['feeling'], 2)\n",
                "        elif counts['simple'] > 0: level = 2 + min(counts['simple'] - 1, 1)\n",
                "        else: level = 0\n",
                "        \n",
                "        if counts['booster'] > 0 and level < 6: level = min(level + 1, 6)\n",
                "        \n",
                "        return {'level': level, 'normalized_score': level / 6.0}\n",
                "\n",
                "print('✅ ReflectionLevelMetric defined')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ========== Word Choice Metric ==========\n",
                "class WordChoiceMetric:\n",
                "    def __init__(self):\n",
                "        self.vad_lexicon = {\n",
                "            'happy': {'v': 0.96, 'a': 0.74, 'd': 0.87},\n",
                "            'excited': {'v': 0.90, 'a': 0.85, 'd': 0.75},\n",
                "            'joy': {'v': 0.98, 'a': 0.78, 'd': 0.82},\n",
                "            'love': {'v': 0.95, 'a': 0.72, 'd': 0.70},\n",
                "            'grateful': {'v': 0.90, 'a': 0.48, 'd': 0.65},\n",
                "            'relieved': {'v': 0.82, 'a': 0.35, 'd': 0.68},\n",
                "            'calm': {'v': 0.78, 'a': 0.22, 'd': 0.72},\n",
                "            'angry': {'v': 0.15, 'a': 0.85, 'd': 0.55},\n",
                "            'scared': {'v': 0.12, 'a': 0.88, 'd': 0.18},\n",
                "            'anxious': {'v': 0.20, 'a': 0.78, 'd': 0.25},\n",
                "            'stressed': {'v': 0.18, 'a': 0.82, 'd': 0.30},\n",
                "            'frustrated': {'v': 0.15, 'a': 0.75, 'd': 0.35},\n",
                "            'overwhelmed': {'v': 0.12, 'a': 0.80, 'd': 0.15},\n",
                "            'sad': {'v': 0.15, 'a': 0.32, 'd': 0.25},\n",
                "            'lonely': {'v': 0.12, 'a': 0.35, 'd': 0.20},\n",
                "            'disappointed': {'v': 0.18, 'a': 0.42, 'd': 0.28},\n",
                "            'understand': {'v': 0.70, 'a': 0.35, 'd': 0.65},\n",
                "            'sorry': {'v': 0.35, 'a': 0.45, 'd': 0.35},\n",
                "            'care': {'v': 0.82, 'a': 0.45, 'd': 0.55},\n",
                "            'support': {'v': 0.78, 'a': 0.48, 'd': 0.62},\n",
                "            'help': {'v': 0.75, 'a': 0.52, 'd': 0.58},\n",
                "            'comfort': {'v': 0.80, 'a': 0.28, 'd': 0.55},\n",
                "            'hear': {'v': 0.58, 'a': 0.38, 'd': 0.52},\n",
                "            'feel': {'v': 0.50, 'a': 0.50, 'd': 0.50},\n",
                "        }\n",
                "    \n",
                "    def compute(self, text: str) -> Dict:\n",
                "        words = re.findall(r'\\b[a-z]+\\b', text.lower())\n",
                "        if not words: return {'valence': 0.5, 'arousal': 0.5, 'dominance': 0.5, 'empathy_alignment': 0.0}\n",
                "        \n",
                "        v_scores, a_scores, d_scores = [], [], []\n",
                "        for w in words:\n",
                "            if w in self.vad_lexicon:\n",
                "                v_scores.append(self.vad_lexicon[w]['v'])\n",
                "                a_scores.append(self.vad_lexicon[w]['a'])\n",
                "                d_scores.append(self.vad_lexicon[w]['d'])\n",
                "        \n",
                "        v = np.mean(v_scores) if v_scores else 0.5\n",
                "        a = np.mean(a_scores) if a_scores else 0.5\n",
                "        d = np.mean(d_scores) if d_scores else 0.5\n",
                "        \n",
                "        # Empathy alignment (ideal: v=0.65, a=0.45, d=0.40)\n",
                "        alignment = 1.0 - (abs(v-0.65) + abs(a-0.45) + abs(d-0.40)) / 3.0\n",
                "        \n",
                "        return {'valence': float(v), 'arousal': float(a), 'dominance': float(d), \n",
                "                'empathy_alignment': max(0.0, min(1.0, alignment))}\n",
                "\n",
                "print('✅ WordChoiceMetric defined')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ========== Diversity Metric ==========\n",
                "class DiversityMetric:\n",
                "    def compute(self, text: str) -> Dict:\n",
                "        tokens = re.findall(r'\\b[a-z]+\\b|[.,!?]', text.lower())\n",
                "        if not tokens: return {'distinct_1': 0.0, 'distinct_2': 0.0, 'diversity_score': 0.0}\n",
                "        \n",
                "        # Distinct-1\n",
                "        d1 = len(set(tokens)) / len(tokens)\n",
                "        \n",
                "        # Distinct-2\n",
                "        bigrams = [tuple(tokens[i:i+2]) for i in range(len(tokens)-1)]\n",
                "        d2 = len(set(bigrams)) / len(bigrams) if bigrams else 0.0\n",
                "        \n",
                "        return {'distinct_1': d1, 'distinct_2': d2, 'diversity_score': 0.4*d1 + 0.6*d2}\n",
                "    \n",
                "    def compute_corpus(self, texts: List[str]) -> Dict:\n",
                "        all_tokens = []\n",
                "        for t in texts:\n",
                "            all_tokens.extend(re.findall(r'\\b[a-z]+\\b|[.,!?]', t.lower()))\n",
                "        if not all_tokens: return {'corpus_distinct_1': 0.0, 'corpus_distinct_2': 0.0}\n",
                "        \n",
                "        d1 = len(set(all_tokens)) / len(all_tokens)\n",
                "        bigrams = [tuple(all_tokens[i:i+2]) for i in range(len(all_tokens)-1)]\n",
                "        d2 = len(set(bigrams)) / len(bigrams) if bigrams else 0.0\n",
                "        \n",
                "        return {'corpus_distinct_1': d1, 'corpus_distinct_2': d2}\n",
                "\n",
                "print('✅ DiversityMetric defined')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ========== Empathy Evaluator ==========\n",
                "@dataclass\n",
                "class EmpathyReport:\n",
                "    model_name: str\n",
                "    num_samples: int\n",
                "    mean_specificity: float\n",
                "    mean_reflection_level: float\n",
                "    mean_word_choice: float\n",
                "    mean_diversity: float\n",
                "    overall_score: float\n",
                "    details: Dict = None\n",
                "    \n",
                "    def to_dict(self): return asdict(self)\n",
                "\n",
                "class EmpathyEvaluator:\n",
                "    def __init__(self):\n",
                "        self.spec = SpecificityMetric()\n",
                "        self.refl = ReflectionLevelMetric()\n",
                "        self.word = WordChoiceMetric()\n",
                "        self.div = DiversityMetric()\n",
                "    \n",
                "    def evaluate(self, responses: List[str], contexts: List[str] = None, \n",
                "                 model_name: str = 'Unknown') -> EmpathyReport:\n",
                "        if contexts is None: contexts = [None] * len(responses)\n",
                "        \n",
                "        spec_scores, refl_scores, word_scores, div_scores = [], [], [], []\n",
                "        \n",
                "        for resp, ctx in zip(responses, contexts):\n",
                "            spec_scores.append(self.spec.compute(resp)['score'])\n",
                "            refl_scores.append(self.refl.compute(resp, ctx)['level'])\n",
                "            word_scores.append(self.word.compute(resp)['empathy_alignment'])\n",
                "            div_scores.append(self.div.compute(resp)['diversity_score'])\n",
                "        \n",
                "        corpus_div = self.div.compute_corpus(responses)\n",
                "        \n",
                "        mean_spec = np.mean(spec_scores)\n",
                "        mean_refl = np.mean(refl_scores)\n",
                "        mean_word = np.mean(word_scores)\n",
                "        mean_div = np.mean(div_scores)\n",
                "        \n",
                "        # Overall score (normalized)\n",
                "        overall = 0.25 * (mean_spec/5.0) + 0.25 * (mean_refl/6.0) + 0.25 * mean_word + 0.25 * mean_div\n",
                "        \n",
                "        return EmpathyReport(\n",
                "            model_name=model_name,\n",
                "            num_samples=len(responses),\n",
                "            mean_specificity=float(mean_spec),\n",
                "            mean_reflection_level=float(mean_refl),\n",
                "            mean_word_choice=float(mean_word),\n",
                "            mean_diversity=float(mean_div),\n",
                "            overall_score=float(overall),\n",
                "            details={'corpus_distinct_2': corpus_div['corpus_distinct_2'],\n",
                "                     'spec_std': float(np.std(spec_scores)),\n",
                "                     'refl_std': float(np.std(refl_scores))}\n",
                "        )\n",
                "    \n",
                "    def print_report(self, report: EmpathyReport):\n",
                "        print('\\n' + '='*60)\n",
                "        print('EMPATHY EVALUATION REPORT')\n",
                "        print('='*60)\n",
                "        print(f'Model: {report.model_name}')\n",
                "        print(f'Samples: {report.num_samples}')\n",
                "        print('-'*40)\n",
                "        print(f'  Specificity:        {report.mean_specificity:.3f} / 5.0')\n",
                "        print(f'  Reflection Level:   {report.mean_reflection_level:.2f} / 6.0')\n",
                "        print(f'  Word Choice:        {report.mean_word_choice:.3f} / 1.0')\n",
                "        print(f'  Diversity:          {report.mean_diversity:.3f} / 1.0')\n",
                "        print('-'*40)\n",
                "        print(f'  OVERALL SCORE:      {report.overall_score:.3f} / 1.0')\n",
                "        print('='*60)\n",
                "\n",
                "evaluator = EmpathyEvaluator()\n",
                "print('✅ EmpathyEvaluator ready!')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["---\n## 3. 테스트 프롬프트 정의"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 공감적 응답이 필요한 상황들\n",
                "TEST_PROMPTS = [\n",
                "    {'context': \"I just lost my job today. I've been working there for 5 years and they just let me go without any warning.\", 'emotion': 'sadness/shock'},\n",
                "    {'context': \"My best friend hasn't talked to me in weeks. I don't know what I did wrong.\", 'emotion': 'confusion/hurt'},\n",
                "    {'context': \"I finally passed my medical exam after failing three times! I can't believe it!\", 'emotion': 'joy/relief'},\n",
                "    {'context': \"My parents are getting divorced after 30 years of marriage. I don't know how to feel.\", 'emotion': 'confusion/sadness'},\n",
                "    {'context': \"I've been feeling really anxious lately. I can't sleep and I keep worrying about everything.\", 'emotion': 'anxiety'},\n",
                "    {'context': 'My dog passed away yesterday. He was with me for 12 years.', 'emotion': 'grief'},\n",
                "    {'context': 'I got accepted into my dream university! All the hard work finally paid off.', 'emotion': 'excitement/pride'},\n",
                "    {'context': \"I feel like nobody understands me. Even my closest friends don't seem to get what I'm going through.\", 'emotion': 'loneliness'},\n",
                "    {'context': \"My partner forgot our anniversary again. It's the third year in a row.\", 'emotion': 'disappointment/hurt'},\n",
                "    {'context': \"I just found out I'm going to be a parent. I'm excited but also terrified.\", 'emotion': 'mixed emotions'},\n",
                "]\n",
                "\n",
                "SYSTEM_PROMPT = '''You are an empathetic listener. When someone shares their feelings or experiences with you, respond with genuine empathy and understanding.\n",
                "- Acknowledge their emotions\n",
                "- Show that you understand their situation  \n",
                "- Be supportive without being dismissive\n",
                "- Avoid giving unsolicited advice unless asked\n",
                "\n",
                "Respond naturally and warmly, as a caring friend would.'''\n",
                "\n",
                "print(f'✅ Loaded {len(TEST_PROMPTS)} test prompts')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["---\n## 4. 모델 로드 함수"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import torch\n",
                "from transformers import AutoTokenizer, AutoModelForCausalLM\n",
                "from tqdm import tqdm\n",
                "import gc\n",
                "\n",
                "def load_model(model_name: str):\n",
                "    '''모델 로드 (H100에서는 양자화 불필요)'''\n",
                "    print(f'\\n{\"=\"*50}')\n",
                "    print(f'Loading: {model_name}')\n",
                "    print(f'{\"=\"*50}')\n",
                "    \n",
                "    tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)\n",
                "    if tokenizer.pad_token is None:\n",
                "        tokenizer.pad_token = tokenizer.eos_token\n",
                "    \n",
                "    model = AutoModelForCausalLM.from_pretrained(\n",
                "        model_name,\n",
                "        device_map='auto',\n",
                "        trust_remote_code=True,\n",
                "        torch_dtype=torch.float16,\n",
                "    )\n",
                "    \n",
                "    print(f'✅ Model loaded! Device: {next(model.parameters()).device}')\n",
                "    return model, tokenizer\n",
                "\n",
                "def generate_response(model, tokenizer, context: str, max_new_tokens: int = 256) -> str:\n",
                "    '''응답 생성'''\n",
                "    if hasattr(tokenizer, 'apply_chat_template') and tokenizer.chat_template:\n",
                "        messages = [{'role': 'system', 'content': SYSTEM_PROMPT}, {'role': 'user', 'content': context}]\n",
                "        prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)\n",
                "    else:\n",
                "        prompt = f'System: {SYSTEM_PROMPT}\\n\\nUser: {context}\\n\\nAssistant:'\n",
                "    \n",
                "    inputs = tokenizer(prompt, return_tensors='pt', truncation=True, max_length=2048)\n",
                "    inputs = {k: v.to(model.device) for k, v in inputs.items()}\n",
                "    \n",
                "    with torch.no_grad():\n",
                "        outputs = model.generate(\n",
                "            **inputs, max_new_tokens=max_new_tokens, temperature=0.7,\n",
                "            do_sample=True, top_p=0.9, pad_token_id=tokenizer.pad_token_id\n",
                "        )\n",
                "    \n",
                "    return tokenizer.decode(outputs[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True).strip()\n",
                "\n",
                "def cleanup():\n",
                "    gc.collect()\n",
                "    torch.cuda.empty_cache()\n",
                "    print('🧹 Memory cleaned!')\n",
                "\n",
                "print('✅ Functions ready!')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["---\n## 5. Llama-3.1-8B 평가"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Llama 모델 로드\n",
                "LLAMA_MODEL = 'meta-llama/Meta-Llama-3.1-8B-Instruct'\n",
                "llama_model, llama_tokenizer = load_model(LLAMA_MODEL)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Llama 응답 생성\n",
                "llama_responses = []\n",
                "llama_contexts = []\n",
                "\n",
                "print('Generating Llama responses...')\n",
                "for prompt_data in tqdm(TEST_PROMPTS):\n",
                "    context = prompt_data['context']\n",
                "    response = generate_response(llama_model, llama_tokenizer, context)\n",
                "    llama_responses.append(response)\n",
                "    llama_contexts.append(context)\n",
                "    print(f'\\n[Context]: {context[:50]}...')\n",
                "    print(f'[Response]: {response[:100]}...')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Llama 평가\n",
                "llama_report = evaluator.evaluate(llama_responses, llama_contexts, LLAMA_MODEL)\n",
                "evaluator.print_report(llama_report)\n",
                "\n",
                "# 결과 저장\n",
                "with open(f'{PROJECT_PATH}/results/llama_evaluation.json', 'w') as f:\n",
                "    json.dump({'model': LLAMA_MODEL, 'responses': llama_responses, 'report': llama_report.to_dict()}, f, indent=2)\n",
                "print(f'✅ Saved to {PROJECT_PATH}/results/llama_evaluation.json')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Llama 메모리 정리\n",
                "del llama_model, llama_tokenizer\n",
                "cleanup()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["---\n## 6. DeepSeek-7B 평가"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# DeepSeek 모델 로드\n",
                "DEEPSEEK_MODEL = 'deepseek-ai/deepseek-llm-7b-chat'\n",
                "deepseek_model, deepseek_tokenizer = load_model(DEEPSEEK_MODEL)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# DeepSeek 응답 생성\n",
                "deepseek_responses = []\n",
                "deepseek_contexts = []\n",
                "\n",
                "print('Generating DeepSeek responses...')\n",
                "for prompt_data in tqdm(TEST_PROMPTS):\n",
                "    context = prompt_data['context']\n",
                "    response = generate_response(deepseek_model, deepseek_tokenizer, context)\n",
                "    deepseek_responses.append(response)\n",
                "    deepseek_contexts.append(context)\n",
                "    print(f'\\n[Context]: {context[:50]}...')\n",
                "    print(f'[Response]: {response[:100]}...')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# DeepSeek 평가\n",
                "deepseek_report = evaluator.evaluate(deepseek_responses, deepseek_contexts, DEEPSEEK_MODEL)\n",
                "evaluator.print_report(deepseek_report)\n",
                "\n",
                "# 결과 저장\n",
                "with open(f'{PROJECT_PATH}/results/deepseek_evaluation.json', 'w') as f:\n",
                "    json.dump({'model': DEEPSEEK_MODEL, 'responses': deepseek_responses, 'report': deepseek_report.to_dict()}, f, indent=2)\n",
                "print(f'✅ Saved to {PROJECT_PATH}/results/deepseek_evaluation.json')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# DeepSeek 메모리 정리\n",
                "del deepseek_model, deepseek_tokenizer\n",
                "cleanup()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["---\n## 7. 모델 비교"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import pandas as pd\n",
                "import matplotlib.pyplot as plt\n",
                "\n",
                "# 비교 테이블\n",
                "comparison = pd.DataFrame({\n",
                "    'Model': ['Llama-3.1-8B', 'DeepSeek-7B'],\n",
                "    'Specificity': [llama_report.mean_specificity, deepseek_report.mean_specificity],\n",
                "    'Reflection': [llama_report.mean_reflection_level, deepseek_report.mean_reflection_level],\n",
                "    'Word Choice': [llama_report.mean_word_choice, deepseek_report.mean_word_choice],\n",
                "    'Diversity': [llama_report.mean_diversity, deepseek_report.mean_diversity],\n",
                "    'Overall': [llama_report.overall_score, deepseek_report.overall_score],\n",
                "})\n",
                "\n",
                "print('\\n' + '='*70)\n",
                "print('MODEL COMPARISON')\n",
                "print('='*70)\n",
                "print(comparison.to_string(index=False))\n",
                "print('='*70)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 레이더 차트\n",
                "categories = ['Specificity\\n(norm)', 'Reflection\\nLevel', 'Word\\nChoice', 'Diversity']\n",
                "N = len(categories)\n",
                "\n",
                "llama_scores = [llama_report.mean_specificity/5, llama_report.mean_reflection_level/6,\n",
                "                llama_report.mean_word_choice, llama_report.mean_diversity]\n",
                "deepseek_scores = [deepseek_report.mean_specificity/5, deepseek_report.mean_reflection_level/6,\n",
                "                   deepseek_report.mean_word_choice, deepseek_report.mean_diversity]\n",
                "\n",
                "angles = [n / N * 2 * np.pi for n in range(N)]\n",
                "angles += angles[:1]\n",
                "llama_scores += llama_scores[:1]\n",
                "deepseek_scores += deepseek_scores[:1]\n",
                "\n",
                "fig, ax = plt.subplots(figsize=(8, 8), subplot_kw=dict(polar=True))\n",
                "ax.plot(angles, llama_scores, 'o-', linewidth=2, label='Llama-3.1-8B', color='#2E86AB')\n",
                "ax.fill(angles, llama_scores, alpha=0.25, color='#2E86AB')\n",
                "ax.plot(angles, deepseek_scores, 'o-', linewidth=2, label='DeepSeek-7B', color='#E94F37')\n",
                "ax.fill(angles, deepseek_scores, alpha=0.25, color='#E94F37')\n",
                "\n",
                "ax.set_xticks(angles[:-1])\n",
                "ax.set_xticklabels(categories, size=12)\n",
                "ax.set_ylim(0, 1)\n",
                "ax.set_title('Empathy Evaluation: Llama vs DeepSeek', size=14, fontweight='bold', pad=20)\n",
                "ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1))\n",
                "\n",
                "plt.tight_layout()\n",
                "plt.savefig(f'{PROJECT_PATH}/results/comparison_radar.png', dpi=150, bbox_inches='tight')\n",
                "plt.show()\n",
                "print(f'\\n✅ Chart saved!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 최종 결과 저장\n",
                "final_result = {\n",
                "    'date': datetime.now().isoformat(),\n",
                "    'models': [LLAMA_MODEL, DEEPSEEK_MODEL],\n",
                "    'llama': llama_report.to_dict(),\n",
                "    'deepseek': deepseek_report.to_dict(),\n",
                "    'winner': LLAMA_MODEL if llama_report.overall_score > deepseek_report.overall_score else DEEPSEEK_MODEL\n",
                "}\n",
                "\n",
                "with open(f'{PROJECT_PATH}/results/baseline_comparison.json', 'w') as f:\n",
                "    json.dump(final_result, f, indent=2)\n",
                "\n",
                "print('\\n' + '='*60)\n",
                "print('🏆 EVALUATION COMPLETE!')\n",
                "print('='*60)\n",
                "print(f\"Winner: {final_result['winner'].split('/')[-1]}\")\n",
                "print(f\"Results saved to: {PROJECT_PATH}/results/\")\n",
                "print('='*60)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["---\n## 8. 응답 샘플 확인"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 응답 비교\n",
                "print('\\n' + '='*80)\n",
                "print('RESPONSE SAMPLES')\n",
                "print('='*80)\n",
                "\n",
                "for i in range(3):\n",
                "    print(f'\\n--- Prompt {i+1} ({TEST_PROMPTS[i][\"emotion\"]}) ---')\n",
                "    print(f'Context: {TEST_PROMPTS[i][\"context\"]}')\n",
                "    print(f'\\n🦙 Llama: {llama_responses[i]}')\n",
                "    print(f'\\n🔷 DeepSeek: {deepseek_responses[i]}')"
            ]
        }
    ]
}

# 노트북 저장
output_path = "01_evaluate_baseline_models.ipynb"
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print(f"✅ Notebook created: {output_path}")
print(f"\n이 파일을 Google Drive의 empathy_alignment 폴더에 업로드하세요!")

